// Ol3-Cesium. See https://github.com/openlayers/ol3-cesium/
// License: https://github.com/openlayers/ol3-cesium/blob/master/LICENSE
// Version: v1.7-61-ge373428

(function(){var k,m=this;function n(a){return void 0!==a}
function p(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function q(a){return"array"==p(a)}function aa(a){var b=p(a);return"array"==b||"object"==b&&"number"==typeof a.length}function r(a){return"string"==typeof a}function ba(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function u(a){return a[ca]||(a[ca]=++da)}var ca="closure_uid_"+(1E9*Math.random()>>>0),da=0;function ea(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function v(a,b,c){v=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return v.apply(null,arguments)}var ga=Date.now||function(){return+new Date};
function w(a,b){var c=a.split("."),d=m;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}}function x(a,b){function c(){}c.prototype=b.prototype;a.Ga=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ja=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};var ha=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function ia(a){if(!ja.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ka,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(la,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ma,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(na,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(oa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(pa,"&#0;"));return a}var ka=/&/g,la=/</g,ma=/>/g,na=/"/g,oa=/'/g,pa=/\x00/g,ja=/[\x00&<>"']/;
function qa(a,b){return a<b?-1:a>b?1:0};function ra(){};var y=Array.prototype;function z(a,b,c){y.forEach.call(a,b,c)}function sa(a,b){var c=y.indexOf.call(a,b,void 0),d;(d=0<=c)&&y.splice.call(a,c,1);return d}function ta(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function ua(a,b){a.sort(b||va)}function wa(a,b){for(var c=0;c<a.length;c++)a[c]={index:c,value:a[c]};var d=b||va;ua(a,function(a,b){return d(a.value,b.value)||a.index-b.index});for(c=0;c<a.length;c++)a[c]=a[c].value}
function va(a,b){return a>b?1:a<b?-1:0};function xa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var ya="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function za(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<ya.length;f++)c=ya[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function A(a,b){this.map=a;this.i=a.getView();this.scene=b;a.getLayerGroup().getLayers();this.b=a.getLayerGroup();this.B={};this.g={};this.c={}}A.prototype.W=function(){Aa(this);Ba(this,this.b)};function B(a,b,c,d){a instanceof ol.layer.Group?(c.push(a),a=a.getLayers(),n(a)&&a.forEach(function(a){B(a,b,c,d)})):(b.push(a),d&&(d[u(a)]=a.getZIndex()))}A.prototype.U=function(){};
function Ba(a,b){var c=[],d=[];B(b,c,d);c.forEach(function(a){if(null!==a){var b=u(a),c=this.B[b],c=this.$(a);null!==c&&(c.zIndex=a.getZIndex(),this.X(c),this.B[b]=c,this.g[b]=a.on("change:zIndex",this.U,this))}},a);d.forEach(function(a){Ca(this,a)},a);a.U()}function Da(a,b){if(b!==a.b){var c=u(b);a.c[c].forEach(function(a){ol.Observable.unByKey(a)});delete a.c[c]}}
function Ea(a,b){if(b){var c=[],d=[];B(b,c,d);c.forEach(function(a){a=u(a);var b=this.B[a];b&&(this.ja(b,!1),this.ba(b),ol.Observable.unByKey(this.g[a]),delete this.g[a]);delete this.B[a]},a);d.forEach(function(a){Da(this,a)},a)}}
function Ca(a,b){var c=u(b),d=[];a.c[c]=d;var e=[],f=v(function(){var a=b.getLayers();n(a)&&(e=[a.on("add",function(a){Ba(this,a.element)},this),a.on("remove",function(a){Ea(this,a.element)},this)],d.push.apply(d,e))},a);f();d.push(b.on("change:layers",function(){z(e,function(a){sa(d,a);ol.Observable.unByKey(a)});f()}))}function Aa(a){a.ia(!0);xa(a.l,function(a){a.forEach(ol.Observable.unByKey)});xa(a.o,ol.Observable.unByKey);a.l={};a.o={};a.B={}};var C;a:{var Fa=m.navigator;if(Fa){var Ga=Fa.userAgent;if(Ga){C=Ga;break a}}C=""}function E(a){return-1!=C.indexOf(a)};var Ha=E("Opera")||E("OPR"),G=E("Trident")||E("MSIE"),Ia=E("Edge"),H=E("Gecko")&&!(-1!=C.toLowerCase().indexOf("webkit")&&!E("Edge"))&&!(E("Trident")||E("MSIE"))&&!E("Edge"),I=-1!=C.toLowerCase().indexOf("webkit")&&!E("Edge");I&&E("Mobile");E("Macintosh");E("Windows");E("Linux")||E("CrOS");var Ja=m.navigator||null;Ja&&(Ja.appVersion||"").indexOf("X11");E("Android");!E("iPhone")||E("iPod")||E("iPad");E("iPad");
function Ka(){var a=C;if(H)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Ia)return/Edge\/([\d\.]+)/.exec(a);if(G)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(I)return/WebKit\/(\S+)/.exec(a)}function La(){var a=m.document;return a?a.documentMode:void 0}var Ma=function(){if(Ha&&m.opera){var a=m.opera.version;return"function"==p(a)?a():a}var a="",b=Ka();b&&(a=b?b[1]:"");return G&&(b=La(),b>parseFloat(a))?String(b):a}(),Na={};
function J(a){var b;if(!(b=Na[a])){b=0;for(var c=ha(String(Ma)).split("."),d=ha(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",l=RegExp("(\\d*)(\\D*)","g"),t=RegExp("(\\d*)(\\D*)","g");do{var F=l.exec(g)||["","",""],D=t.exec(h)||["","",""];if(0==F[0].length&&0==D[0].length)break;b=qa(0==F[1].length?0:parseInt(F[1],10),0==D[1].length?0:parseInt(D[1],10))||qa(0==F[2].length,0==D[2].length)||qa(F[2],D[2])}while(0==b)}b=Na[a]=0<=b}return b}
var Oa=m.document,Pa=Oa&&G?La()||("CSS1Compat"==Oa.compatMode?parseInt(Ma,10):5):void 0;var Qa=!G||9<=Pa,Ra=G&&!J("9");!I||J("528");H&&J("1.9b")||G&&J("8")||Ha&&J("9.5")||I&&J("528");H&&!J("8")||G&&J("9");function K(){0!=Sa&&u(this);this.h=this.h;this.za=this.za}var Sa=0;K.prototype.h=!1;function L(a,b){this.type=a;this.a=this.target=b}L.prototype.b=function(){};function Ta(a){Ta[" "](a);return a}Ta[" "]=function(){};function M(a,b){L.call(this,a?a.type:"");this.c=this.a=this.target=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;if(c&&H)try{Ta(c.nodeName)}catch(d){}this.c=a;a.defaultPrevented&&this.b()}}x(M,L);M.prototype.b=function(){M.Ga.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Ra)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var N="closure_listenable_"+(1E6*Math.random()|0),Ua=0;function Va(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.L=!!d;this.M=e;++Ua;this.I=this.K=!1}function Wa(a){a.I=!0;a.listener=null;a.proxy=null;a.src=null;a.M=null};function O(a){this.src=a;this.a={};this.b=0}O.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=Xa(a,b,d,e);-1<g?(b=a[g],c||(b.K=!1)):(b=new Va(b,this.src,f,!!d,e),b.K=c,a.push(b));return b};O.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Xa(e,b,c,d);return-1<b?(Wa(e[b]),y.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
function Ya(a,b){var c=b.type;c in a.a&&sa(a.a[c],b)&&(Wa(b),0==a.a[c].length&&(delete a.a[c],a.b--))}function Xa(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.I&&f.listener==b&&f.L==!!c&&f.M==d)return e}return-1};var Za="closure_lm_"+(1E6*Math.random()|0),$a={},ab=0;function bb(a,b,c,d,e){if(q(b)){for(var f=0;f<b.length;f++)bb(a,b[f],c,d,e);return null}c=eb(c);return a&&a[N]?a.o(b,c,d,e):fb(a,b,c,!1,d,e)}
function fb(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=!!e,h=P(a);h||(a[Za]=h=new O(a));c=h.add(b,c,d,e,f);if(c.proxy)return c;d=gb();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,g);else if(a.attachEvent)a.attachEvent(hb(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");ab++;return c}
function gb(){var a=ib,b=Qa?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function jb(a,b,c,d,e){if(q(b))for(var f=0;f<b.length;f++)jb(a,b[f],c,d,e);else c=eb(c),a&&a[N]?a.F.add(String(b),c,!0,d,e):fb(a,b,c,!0,d,e)}function kb(a,b,c,d,e){if(q(b))for(var f=0;f<b.length;f++)kb(a,b[f],c,d,e);else(c=eb(c),a&&a[N])?a.F.remove(String(b),c,d,e):a&&(a=P(a))&&(b=a.a[b.toString()],a=-1,b&&(a=Xa(b,c,!!d,e)),(c=-1<a?b[a]:null)&&Q(c))}
function Q(a){if("number"!=typeof a&&a&&!a.I){var b=a.src;if(b&&b[N])Ya(b.F,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.L):b.detachEvent&&b.detachEvent(hb(c),d);ab--;(c=P(b))?(Ya(c,a),0==c.b&&(c.src=null,b[Za]=null)):Wa(a)}}}function hb(a){return a in $a?$a[a]:$a[a]="on"+a}function lb(a,b,c,d){var e=!0;if(a=P(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.L==c&&!f.I&&(f=mb(f,d),e=e&&!1!==f)}return e}
function mb(a,b){var c=a.listener,d=a.M||a.src;a.K&&Q(a);return c.call(d,b)}
function ib(a,b){if(a.I)return!0;if(!Qa){var c;if(!(c=b))a:{c=["window","event"];for(var d=m,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new M(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(l){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,g=e.length-1;0<=g;g--){c.a=e[g];var h=lb(e[g],f,!0,c),d=d&&h}for(g=0;g<e.length;g++)c.a=e[g],h=lb(e[g],f,!1,c),
d=d&&h}return d}return mb(a,new M(b,this))}function P(a){a=a[Za];return a instanceof O?a:null}var nb="__closure_events_fn_"+(1E9*Math.random()>>>0);function eb(a){if("function"==p(a))return a;a[nb]||(a[nb]=function(b){return a.handleEvent(b)});return a[nb]};function ob(a){var b;b=b||0;return function(){return a.apply(this,Array.prototype.slice.call(arguments,0,b))}};function R(a,b,c){K.call(this);this.a=null;this.g=!1;this.o=a;this.l=c;this.b=b||window;this.c=v(this.i,this)}x(R,K);R.prototype.start=function(){pb(this);this.g=!1;var a=qb(this),b=rb(this);a&&!b&&this.b.mozRequestAnimationFrame?(this.a=bb(this.b,"MozBeforePaint",this.c),this.b.mozRequestAnimationFrame(null),this.g=!0):this.a=a&&b?a.call(this.b,this.c):this.b.setTimeout(ob(this.c),20)};
function pb(a){if(null!=a.a){var b=qb(a),c=rb(a);b&&!c&&a.b.mozRequestAnimationFrame?Q(a.a):b&&c?c.call(a.b,a.a):a.b.clearTimeout(a.a)}a.a=null}R.prototype.i=function(){this.g&&this.a&&Q(this.a);this.a=null;this.o.call(this.l,ga())};function qb(a){a=a.b;return a.requestAnimationFrame||a.webkitRequestAnimationFrame||a.mozRequestAnimationFrame||a.oRequestAnimationFrame||a.msRequestAnimationFrame||null}
function rb(a){a=a.b;return a.cancelAnimationFrame||a.cancelRequestAnimationFrame||a.webkitCancelRequestAnimationFrame||a.mozCancelRequestAnimationFrame||a.oCancelRequestAnimationFrame||a.msCancelRequestAnimationFrame||null};function S(a,b){this.a=a;this.b=null;this.o=n(b)?b:null;this.h=!1;this.l=new Cesium.Event;this.c=document.createElement(sb);this.c.width=1;this.c.height=1;this.a.on("change",function(){tb(this)},this);tb(this)}
Object.defineProperties(S.prototype,{ready:{get:function(){return this.h}},rectangle:{get:function(){return this.A}},tileWidth:{get:function(){var a=this.a.getTileGrid();return null===a?256:a.getTileSize(0)}},tileHeight:{get:function(){return this.tileWidth}},maximumLevel:{get:function(){var a=this.a.getTileGrid();return null===a?18:a.getMaxZoom()}},minimumLevel:{get:function(){return 0}},tilingScheme:{get:function(){return this.g}},tileDiscardPolicy:{get:function(){}},errorEvent:{get:function(){return this.l}},
credit:{get:function(){return this.i}},proxy:{get:function(){}},hasAlphaChannel:{get:function(){return!0}},Ka:{get:function(){}}});function tb(a){if(!a.h&&"ready"==a.a.getState()){var b=a.a.getProjection();a.b=null!=b?b:a.o;if(a.b==ol.proj.get("EPSG:4326"))a.g=new Cesium.GeographicTilingScheme;else if(a.b==ol.proj.get("EPSG:3857"))a.g=new Cesium.WebMercatorTilingScheme;else return;a.A=a.g.rectangle;b=ub(a.a);a.i=null===b?void 0:b;a.h=!0}}
function ub(a){var b="",c=a.getAttributions();null===c||z(c,function(a){b+=a.getHTML().replace(/<\/?[^>]+(>|$)/g,"")+" "});var d,e;0==b.length&&(a=a.getLogo(),n(a)&&(r(a)?d=a:(d=a.src,e=a.href)));return n(d)||0<b.length?new Cesium.Credit(b,d,e):null}S.prototype.getTileCredits=function(){};S.prototype.getTileCredits=S.prototype.getTileCredits;
S.prototype.requestImage=function(a,b,c){var d=this.a.getTileUrlFunction();if(null===d||null===this.b)return this.c;a=d([this.g instanceof Cesium.GeographicTilingScheme?c+1:c,a,-b-1],1,this.b);return n(a)?Cesium.ImageryProvider.loadImage(this,a):this.c};S.prototype.requestImage=S.prototype.requestImage;function vb(a,b,c,d,e){var f=Cesium.Math.clamp,g=Cesium.defaultValue;e=e||{};var h=g(e.duration,500),l=g(e.easing,ol.easing.linear),t=e.callback,F=ga(),D=0,cb=new Cesium.Matrix4,db=new R(function(e){e=l(f((e-F)/h,0,1));a.transform.clone(cb);var g=(e-D)*b;D=e;a.lookAtTransform(d);a.rotate(c,g);a.lookAtTransform(cb);1>e?db.start():t&&t()});db.start()}function wb(a,b){var c=a.camera.getPickRay(b);return a.globe.pick(c,a)||a.camera.pickEllipsoid(b)}
function xb(a){var b=a.canvas,b=new Cesium.Cartesian2(b.width/2,b.height/2);return wb(a,b)}function yb(a,b,c){var d=new Cesium.Cartesian3,e=new Cesium.Cartesian3,f=new Cesium.Cartesian3;Cesium.Cartesian3.normalize(a,d);Cesium.Cartesian3.normalize(b,e);Cesium.Cartesian3.cross(d,e,f);a=Cesium.Cartesian3.dot(d,e);b=Cesium.Cartesian3.magnitude(f);c=Cesium.Cartesian3.dot(c,f);f=Math.atan2(b,a);return 0<=c?f:-f}
function zb(a,b){var c=a.camera,d=c.frustum.fovy/2,e;e=a.camera;var f=e.direction,g=Cesium.Quaternion.fromAxisAngle(e.right,e.frustum.fovy/2),g=Cesium.Matrix3.fromQuaternion(g),h=new Cesium.Cartesian3;Cesium.Matrix3.multiplyByVector(g,f,h);e=new Cesium.Ray(e.position,h);e=Cesium.Cartesian3.clone(e.direction);Cesium.Cartesian3.negate(e,e);f=new Cesium.Cartesian3;Cesium.Ellipsoid.WGS84.geocentricSurfaceNormal(b,f);g=new Cesium.Cartesian3;Cesium.Cartesian3.negate(c.right,g);return yb(f,e,g)+d}
function Ab(a,b,c){n(c)&&(c=c.getHeight(b),b.height=n(c)?c:0);c=Cesium.Ellipsoid.WGS84;b=c.cartographicToCartesian(b);var d=a.position,e=new Cesium.Cartesian3;c.geocentricSurfaceNormal(d,e);a.lookAt(d,b,e)}function Bb(a,b){if(null===a||null===b)return null;var c=ol.proj.transformExtent(a,b,"EPSG:4326");return Cesium.Rectangle.fromDegrees(c[0],c[1],c[2],c[3])}
function Cb(a,b){if(!(a instanceof ol.layer.Tile))return null;var c=null,c=a.getSource();if(!(c instanceof ol.source.WMTS)&&c instanceof ol.source.TileImage){var d=c.getProjection();if(null===d)d=b;else if(d!==b)return null;var e=d===ol.proj.get("EPSG:3857"),d=d===ol.proj.get("EPSG:4326");if(e||d)c=new S(c,b);else return null}else return null;e={};d=a.getExtent();null!=d&&null!==b&&(e.rectangle=Bb(d,b));return new Cesium.ImageryLayer(c,e)}
function Db(a,b){var c=a.getOpacity();n(c)&&(b.alpha=c);c=a.getVisible();n(c)&&(b.show=c);c=a.getSaturation();n(c)&&(b.saturation=c);c=a.getContrast();n(c)&&(b.contrast=c);c=a.getBrightness();n(c)&&(b.brightness=Math.pow(1+parseFloat(c),2))}function T(a){return 2<a.length?Cesium.Cartesian3.fromDegrees(a[0],a[1],a[2]):Cesium.Cartesian3.fromDegrees(a[0],a[1])}function Eb(a){for(var b=[],c=0;c<a.length;++c)b.push(T(a[c]));return b}
function U(a,b){var c=ol.proj.get("EPSG:4326"),d=ol.proj.get(b);if(d!==c){var e=a.getProperties();a=a.clone();a.transform(d,c);a.setProperties(e)}return a}function Fb(a){a=a||"black";if(q(a))return new Cesium.Color(Cesium.Color.byteToFloat(a[0]),Cesium.Color.byteToFloat(a[1]),Cesium.Color.byteToFloat(a[2]),a[3]);if(r(a))return Cesium.Color.fromCssColorString(a)};function V(a,b){this.f=a;this.b=a.camera;this.j=b;this.o=this.a=null;this.h=this.c=Gb;this.g=this.i=0;this.l=null;this.A=!1;this.j.on("change:view",function(){Hb(this,this.j.getView())},this);Hb(this,this.j.getView())}function Gb(a,b,c){c=c||a.length;if(b)for(var d=0;d<c;++d)b[d]=a[d];return a}
function Hb(a,b){null!==a.a&&(ol.Observable.unByKey(a.o),a.o=null);a.a=b;if(null===b)a.c=Gb,a.h=Gb;else{var c=ol.proj.getTransform(b.getProjection(),"EPSG:4326"),d=ol.proj.getTransform("EPSG:4326",b.getProjection());a.c=c;a.h=d;a.o=b.on("propertychange",a.ra,a);a.H()}}k=V.prototype;k.ra=function(){this.A||this.H()};k.Ea=function(a){null===this.a||this.a.setRotation(a)};k.ua=function(){if(null!==this.a){var a=this.a.getRotation();return n(a)?a:0}};k.Fa=function(a){this.i=a;Ib(this)};k.qa=function(){return this.i};
k.Ca=function(a){this.g=a;Ib(this);this.C()};k.na=function(){return this.g};k.xa=function(a){null===this.a||this.a.setCenter(a)};k.getCenter=function(){return null===this.a?void 0:this.a.getCenter()};k.ya=function(a){null!==this.c&&(a=this.c(a),a=new Cesium.Cartographic(a[0]*Math.PI/180,a[1]*Math.PI/180,this.ha()),this.b.position=Cesium.Ellipsoid.WGS84.cartographicToCartesian(a),this.C())};
k.va=function(){if(null!==this.h){var a=Cesium.Ellipsoid.WGS84.cartesianToCartographic(this.b.position);return this.h([180*a.longitude/Math.PI,180*a.latitude/Math.PI])}};k.Aa=function(a){var b=Cesium.Ellipsoid.WGS84.cartesianToCartographic(this.b.position);b.height=a;this.b.position=Cesium.Ellipsoid.WGS84.cartographicToCartesian(b);this.C()};k.ha=function(){return Cesium.Ellipsoid.WGS84.cartesianToCartographic(this.b.position).height};
k.wa=function(a){null!==this.c&&(a=this.c(a),a=Cesium.Cartographic.fromDegrees(a[0],a[1]),Ab(this.b,a,this.f.globe),this.C())};function Ib(a){if(null!==a.a&&null!==a.c){var b=a.a.getCenter();if(b){b=a.c(b);b=new Cesium.Cartographic(b[0]*Math.PI/180,b[1]*Math.PI/180);if(a.f.globe){var c=a.f.globe.getHeight(b);b.height=n(c)?c:0}a.b.setView({positionCartographic:b,pitch:a.i-Cesium.Math.PI_OVER_TWO,heading:-a.a.getRotation()});a.b.moveBackward(a.g);Jb(a,!0)}}}
k.H=function(){if(null!==this.a&&null!==this.c){var a=this.a.getCenter();if(null!=a){var b=this.c(a),a=this.a.getResolution(),a=n(a)?a:0,b=b[1]*Math.PI/180,c=this.f.canvas,d=this.b.frustum.fovy,e=this.a.getProjection().getMetersPerUnit();this.g=a*c.height*e*Math.cos(Math.abs(b))/2/Math.tan(d/2);Ib(this)}}};
k.C=function(){if(null!==this.a&&null!==this.h){this.A=!0;var a=Cesium.Ellipsoid.WGS84,b=this.f,c=xb(b),d=c;d||(d=b.globe,b=this.b.positionCartographic.clone(),d=d.getHeight(b),b.height=n(d)?d:0,d=Cesium.Ellipsoid.WGS84.cartographicToCartesian(b));this.g=Cesium.Cartesian3.distance(d,this.b.position);b=a.cartesianToCartographic(d);this.a.setCenter(this.h([180*b.longitude/Math.PI,180*b.latitude/Math.PI]));this.a.setResolution(Kb(this,this.g,b?b.latitude:0));if(c){d=this.b.position;b=new Cesium.Cartesian3;
a.geocentricSurfaceNormal(c,b);a=new Cesium.Cartesian3;Cesium.Cartesian3.subtract(d,c,a);Cesium.Cartesian3.normalize(a,a);var d=this.b.up,e=this.b.right,f=new Cesium.Cartesian3(-c.y,c.x,0),e=Cesium.Cartesian3.angleBetween(e,f),c=Cesium.Cartesian3.cross(c,d,new Cesium.Cartesian3).z;this.a.setRotation(0>c?e:-e);c=Math.acos(Cesium.Cartesian3.dot(b,a));this.i=isNaN(c)?0:c}else this.a.setRotation(this.b.heading),this.i=-this.b.pitch+Math.PI/2;this.A=!1}};
function Jb(a,b){var c=a.b.viewMatrix;a.l&&a.l.equals(c)||(a.l=c.clone(),!0!==b&&a.C())}function Kb(a,b,c){var d=a.f.canvas,e=a.b.frustum.fovy;a=a.a.getProjection().getMetersPerUnit();return 2*b*Math.tan(e/2)/a/Math.cos(Math.abs(c))/d.height};function Lb(a,b){var c=new Cesium.BillboardCollection({scene:b}),d=new Cesium.PrimitiveCollection;this.b=[];this.a=new Cesium.PrimitiveCollection;this.c={projection:a,billboards:c,featureToCesiumMap:{},primitives:d};this.a.add(c);this.a.add(d)}Lb.prototype.destroy=function(){this.b.forEach(ol.Observable.unByKey);this.b.length=0};function W(){K.call(this);this.F=new O(this);this.A=this}x(W,K);W.prototype[N]=!0;W.prototype.removeEventListener=function(a,b,c,d){kb(this,a,b,c,d)};function Mb(a,b){var c=a.A,d=b,e=d.type||d;if(r(d))d=new L(d,c);else if(d instanceof L)d.target=d.target||c;else{var f=d,d=new L(e,c);za(d,f)}c=d.a=c;Nb(c,e,!0,d);Nb(c,e,!1,d)}W.prototype.o=function(a,b,c,d){return this.F.add(String(a),b,!1,c,d)};
function Nb(a,b,c,d){if(b=a.F.a[String(b)]){b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.I&&g.L==c){var h=g.listener,l=g.M||g.src;g.K&&Ya(a.F,g);e=!1!==h.call(l,d)&&e}}}};function X(a){a=n(a)?a:{};W.call(this);this.b=this.f=null;this.a=new Cesium.RectanglePrimitive({asynchronous:!1,rectangle:new Cesium.Rectangle,material:Cesium.Material.fromType(Cesium.Material.ColorType)});this.a.material.uniforms.color=new Cesium.Color(0,0,1,.5);this.c=n(a.sa)?a.sa:Cesium.KeyboardEventModifier.SHIFT;this.g=null}x(X,W);
X.prototype.ta=function(a){var b=this.f.globe.ellipsoid;a=this.f.camera.getPickRay(a.position);a=this.f.globe.pick(a,this.f);n(a)&&(this.b.setInputAction(v(this.i,this),Cesium.ScreenSpaceEventType.MOUSE_MOVE),this.b.setInputAction(v(this.l,this),Cesium.ScreenSpaceEventType.LEFT_UP),n(this.c)&&(this.b.setInputAction(v(this.i,this),Cesium.ScreenSpaceEventType.MOUSE_MOVE,this.c),this.b.setInputAction(v(this.l,this),Cesium.ScreenSpaceEventType.LEFT_UP,this.c)),b=b.cartesianToCartographic(a),a=this.a.rectangle,
a.north=a.south=b.latitude,a.east=a.west=b.longitude,this.a.height=b.height,this.a.show=!0,Mb(this,{type:"boxstart",position:b}),this.f.primitives.contains(this.a)||this.f.primitives.add(this.a),this.f.screenSpaceCameraController.enableInputs=!1,this.g=b)};
X.prototype.i=function(a){var b=this.f.globe.ellipsoid;a=this.f.camera.getPickRay(a.endPosition);a=this.f.globe.pick(a,this.f);n(a)&&(b=b.cartesianToCartographic(a),this.a.height=Math.max(this.a.height,b.height),b.latitude<this.g.latitude?this.a.rectangle.south=b.latitude:this.a.rectangle.north=b.latitude,b.longitude<this.g.longitude?this.a.rectangle.west=b.longitude:this.a.rectangle.east=b.longitude)};
X.prototype.l=function(a){var b=this.f.globe.ellipsoid;a=this.f.camera.getPickRay(a.position);a=this.f.globe.pick(a,this.f);n(a)&&(b=b.cartesianToCartographic(a),this.a.show=!1,Mb(this,{type:"boxend",position:b}),this.b.removeInputAction(Cesium.ScreenSpaceEventType.LEFT_UP),this.b.removeInputAction(Cesium.ScreenSpaceEventType.MOUSE_MOVE),n(this.c)&&(this.b.removeInputAction(Cesium.ScreenSpaceEventType.LEFT_UP,this.c),this.b.removeInputAction(Cesium.ScreenSpaceEventType.MOUSE_MOVE,this.c)));this.f.screenSpaceCameraController.enableInputs=
!0};X.prototype.Ha=function(a){null===a?(this.f.primitives.contains(this.a)&&this.f.primitives.remove(this.a),null!==this.b&&(this.b.destroy(),this.b=null)):(this.b=new Cesium.ScreenSpaceEventHandler(a.canvas),this.b.setInputAction(v(this.ta,this),Cesium.ScreenSpaceEventType.LEFT_DOWN,this.c));this.f=a};function Y(a){this.scene=a}function Ob(a,b,c,d,e){var f={flat:!0,renderState:{depthTest:{enabled:!0}}};n(e)&&(f.renderState||(f.renderState={}),f.renderState.lineWidth=e);e=new Cesium.PerInstanceColorAppearance(f);c=new Cesium.GeometryInstance({geometry:c,attributes:{color:Cesium.ColorGeometryInstanceAttribute.fromColor(d)}});c=new Cesium.Primitive({geometryInstances:c,appearance:e});c.olLayer=a;c.olFeature=b;return c}
function Pb(a,b){var c=a.getFill()?a.getFill().getColor():null,d=a.getStroke()?a.getStroke().getColor():null,e="black";d&&b?e=d:c&&(e=c);return Fb(e)}function Qb(a,b){var c=b.getStroke()?b.getStroke().getWidth():1;return Math.min(c,a.scene.maximumAliasedLineWidth)}function Rb(a,b,c,d,e,f){var g=Pb(f,!1),h=Pb(f,!0),l=new Cesium.PrimitiveCollection;f.getFill()&&(d=Ob(b,c,d,g),l.add(d));f.getStroke()&&(a=Qb(a,f),d=Ob(b,c,e,h,a),l.add(d));return l}
function Sb(a,b,c,d,e,f){var g;f instanceof Cesium.PrimitiveCollection?g=f:(g=new Cesium.PrimitiveCollection,g.add(f));if(!e.getText())return g;e=e.getText();(a=a.da(b,c,d,e))&&g.add(a);return g}k=Y.prototype;k.aa=function(a,b,c,d){a=a.add(b);a.olLayer=c;a.olFeature=d;return a};
k.ca=function(a,b,c,d,e){c=U(c,d);d=c.getCenter();var f=3==d.length?d[2]:0,g=d.slice();g[0]+=c.getRadius();d=T(d);var g=T(g),h=Cesium.Cartesian3.distance(d,g),g=new Cesium.CircleGeometry({center:d,radius:h,height:f});d=new Cesium.CircleOutlineGeometry({center:d,radius:h,extrudedHeight:f,height:f});d=Rb(this,a,b,g,d,e);return Sb(this,a,b,c,e,d)};
k.S=function(a,b,c,d,e){c=U(c,d);var f=Eb(c.getCoordinates());d=new Cesium.PolylineMaterialAppearance({material:this.fa(0,e,!0)});f=new Cesium.PolylineGeometry({positions:f,width:Qb(this,e),vertexFormat:d.vertexFormat});d=new Cesium.Primitive({geometryInstances:new Cesium.GeometryInstance({geometry:f}),appearance:d});d.olLayer=a;d.olFeature=b;return Sb(this,a,b,c,e,d)};
k.T=function(a,b,c,d,e){c=U(c,d);for(var f=c.getLinearRings(),g=d={},h=0;h<f.length;++h){var l=f[h].getCoordinates(),l=Eb(l);0==h?d.positions=l:(d.holes={positions:l},d=d.holes)}f=new Cesium.PolygonGeometry({polygonHierarchy:g,perPositionHeight:!0});d=new Cesium.PolygonOutlineGeometry({polygonHierarchy:d,perPositionHeight:!0});d=Rb(this,a,b,f,d,e);return Sb(this,a,b,c,e,d)};
k.R=function(a,b,c){c=c.get("altitudeMode");n(c)||(c=b.get("altitudeMode"));n(c)||(c=a.get("altitudeMode"));a=Cesium.HeightReference.NONE;"clampToGround"===c?a=Cesium.HeightReference.CLAMP_TO_GROUND:"relativeToGround"===c&&(a=Cesium.HeightReference.RELATIVE_TO_GROUND);return a};
k.O=function(a,b,c,d,e,f,g){c=U(c,d);var h=e.getImage();h instanceof ol.style.Icon&&h.load();var l=h.getImage(1),t=v(function(){if(null!==l&&(l instanceof HTMLCanvasElement||l instanceof Image||l instanceof HTMLImageElement)){var d=c.getCoordinates(),d=T(d),e,t=h.getOpacity();n(t)&&(e=new Cesium.Color(1,1,1,t));t=this.R(a,b,c);e=this.aa(f,{image:l,color:e,heightReference:t,verticalOrigin:Cesium.VerticalOrigin.BOTTOM,position:d},a,b);g&&g(e)}},this);l instanceof Image&&(""==l.src||0==l.naturalHeight||
0==l.naturalWidth||!l.complete)?jb(l,"load",function(){f.isDestroyed()||t()}):t();return e.getText()?Sb(this,a,b,c,e,new Cesium.Primitive):null};
k.ea=function(a,b,c,d,e,f,g){function h(c,f){var g=new Cesium.PrimitiveCollection;z(c,function(c){g.add(f(a,b,c,d,e))});return g}switch(c.getType()){case "MultiPoint":c=c.getPoints();if(e.getText()){var l=new Cesium.PrimitiveCollection;z(c,function(c){(c=this.O(a,b,c,d,e,f,g))&&l.add(c)}.bind(this));return l}z(c,function(c){this.O(a,b,c,d,e,f,g)});return null;case "MultiLineString":return c=c.getLineStrings(),h(c,this.S.bind(this));case "MultiPolygon":return c=c.getPolygons(),h(c,this.T.bind(this));
default:ra("Unhandled multi geometry type"+c.getType())}};
k.da=function(a,b,c,d){var e=d.getText(),f=new Cesium.LabelCollection({scene:this.scene}),g=ol.extent.getCenter(c.getExtent());if(c instanceof ol.geom.SimpleGeometry){var h=c.getFirstCoordinate();g[2]=3==h.length?h[2]:0}h={};h.position=T(g);h.text=e;h.heightReference=this.R(a,b,c);c=d.getOffsetX();e=d.getOffsetY();0!=c&&0!=e&&(c=new Cesium.Cartesian2(c,e),h.pixelOffset=c);c=d.getFont();null!=c&&(h.font=c);c=void 0;d.getFill()&&(h.fillColor=Pb(d,!1),c=Cesium.LabelStyle.FILL);d.getStroke()&&(h.outlineWidth=
Qb(this,d),h.outlineColor=Pb(d,!0),c=Cesium.LabelStyle.OUTLINE);d.getFill()&&d.getStroke()&&(c=Cesium.LabelStyle.FILL_AND_OUTLINE);h.style=c;if(d.getTextAlign()){var l;switch(d.getTextAlign()){case "center":l=Cesium.HorizontalOrigin.CENTER;break;case "left":l=Cesium.HorizontalOrigin.LEFT;break;case "right":l=Cesium.HorizontalOrigin.RIGHT;break;default:d.getTextAlign()}h.horizontalOrigin=l}if(d.getTextBaseline()){var t;switch(d.getTextBaseline()){case "top":t=Cesium.VerticalOrigin.TOP;break;case "middle":t=
Cesium.VerticalOrigin.CENTER;break;case "bottom":t=Cesium.VerticalOrigin.BOTTOM;break;case "alphabetic":t=Cesium.VerticalOrigin.TOP;break;case "hanging":t=Cesium.VerticalOrigin.BOTTOM;break;default:d.getTextBaseline()}h.verticalOrigin=t}d=f.add(h);d.olLayer=a;d.olFeature=b;return f};
k.fa=function(a,b,c){a=b.getFill();b=b.getStroke();if(c&&!b||!c&&!a)return null;a=c?b.getColor():a.getColor();a=Fb(a);return c&&b.getLineDash()?Cesium.Material.fromType("Stripe",{horizontal:!1,repeat:500,evenColor:a,oddColor:new Cesium.Color(0,0,0,0)}):Cesium.Material.fromType("Color",{color:a})};k.P=function(a,b,c,d){a=b.getStyleFunction();var e;n(a)&&(e=a.call(b,d));null==e&&null!=c&&(e=c(b,d));return n(e)?e[0]:null};
k.N=function(a,b,c,d,e){function f(a){d.featureToCesiumMap[u(b)]=a}e=e||b.getGeometry();var g=d.projection;if(!e)return null;switch(e.getType()){case "GeometryCollection":var h=new Cesium.PrimitiveCollection;z(e.getGeometries(),function(e){e&&(e=this.N(a,b,c,d,e))&&h.add(e)}.bind(this));return h;case "Point":return(e=this.O(a,b,e,g,c,d.billboards,f))?e:null;case "Circle":return this.ca(a,b,e,g,c);case "LineString":return this.S(a,b,e,g,c);case "Polygon":return this.T(a,b,e,g,c);case "MultiPoint":case "MultiLineString":case "MultiPolygon":return(e=
this.ea(a,b,e,g,c,d.billboards,f))?e:null;case "LinearRing":throw Error("LinearRing should only be part of polygon.");default:throw Error("Ol geom type not handled : "+e.getType());}};k.ga=function(a,b,c){var d=a.getSource().getFeatures(),e=b.getProjection();b=b.getResolution();if(!n(b)||!e)throw Error("View not ready");for(var e=new Lb(e,this.scene),f=e.c,g=0;g<d.length;++g){var h=d[g];if(null!=h){var l=a.getStyleFunction();if(l=this.P(0,h,l,b))if(l=this.N(a,h,l,f))c[u(h)]=l,e.a.add(l)}}return e};
k.Z=function(a,b,c,d){var e=b.getProjection();b=b.getResolution();if(!n(b)||!e)return null;var f=a.getStyleFunction();b=this.P(0,c,f,b);if(!b)return null;d.projection=e;return this.N(a,c,b,d)};var Tb=!G||9<=Pa;!H&&!G||G&&9<=Pa||H&&J("1.9.1");G&&J("9");var sb="CANVAS";function Ub(a){var b=document;return r(a)?b.getElementById(a):a}
function Vb(a){var b=a||document,c=null;if(b.getElementsByClassName)c=b.getElementsByClassName("ol-overlaycontainer")[0];else if(b.querySelectorAll&&b.querySelector)c=b.querySelector(".ol-overlaycontainer");else{var d,b=document;a=a||b;if(a.querySelectorAll&&a.querySelector)a=a.querySelectorAll(".ol-overlaycontainer");else if(a.getElementsByClassName){var e=a.getElementsByClassName("ol-overlaycontainer");a=e}else{e=a.getElementsByTagName("*");d={};for(b=c=0;a=e[b];b++){var f=a.className,g;if(g="function"==
typeof f.split)g=0<=y.indexOf.call(f.split(/\s+/),"ol-overlaycontainer",void 0);g&&(d[c++]=a)}d.length=c;a=d}c=a[0]}return c||null}function Wb(a,b){xa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Xb.hasOwnProperty(d)?a.setAttribute(Xb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}
var Xb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Yb(a,b,c){var d=arguments,e=document,f=d[0],g=d[1];if(!Tb&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',ia(g.name),'"');if(g.type){f.push(' type="',ia(g.type),'"');var h={};za(h,g);delete h.type;g=h}f.push(">");f=f.join("")}f=e.createElement(f);g&&(r(g)?f.className=g:q(g)?f.className=g.join(" "):Wb(f,g));2<d.length&&Zb(e,f,d);return f}
function Zb(a,b,c){function d(c){c&&b.appendChild(r(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];if(!aa(f)||ba(f)&&0<f.nodeType)d(f);else{var g;a:{if(f&&"number"==typeof f.length){if(ba(f)){g="function"==typeof f.item||"string"==typeof f.item;break a}if("function"==p(f)){g="function"==typeof f.item;break a}}g=!1}z(g?ta(f):f,d)}}}function $b(a){if(n(a.nextElementSibling))a=a.nextElementSibling;else for(a=a.nextSibling;a&&1!=a.nodeType;)a=a.nextSibling;return a};function ac(a,b){this.u=b.imageryLayers;this.G=new Cesium.ImageryLayerCollection;A.call(this,a,b)}x(ac,A);k=ac.prototype;k.X=function(a){this.u.add(a);this.G.add(a)};k.ba=function(a){a.destroy()};k.ja=function(a,b){this.u.remove(a,b);this.G.remove(a,!1)};k.ia=function(a){for(var b=0;b<this.G.length;++b)this.u.remove(this.G.get(b),a);this.G.removeAll(!1)};k.ka=Cb;
k.$=function(a){var b=this.i.getProjection(),c=this.ka(a,b);null!==c&&(a.on("change:brightness change:contrast change:hue change:opacity change:saturation change:visible".split(" "),function(){null===c||Db(a,c)}),Db(a,c),a.on("change:extent",function(){this.u.remove(c,!0);this.G.remove(c,!1);delete this.B[u(a)];this.W()},this),a.on("change",function(){var a=this.u.indexOf(c);0<=a&&(this.u.remove(c,!1),this.u.add(c,a))},this));return c};
k.U=function(){var a=[],b={};B(this.b,a,[],b);wa(a,function(a,d){return b[u(a)]-b[u(d)]});a.forEach(function(a){a=u(a);(a=this.B[a])&&this.u.raiseToTop(a)},this)};function bc(a,b,c){this.h=c||new Y(b);this.a=new Cesium.PrimitiveCollection;b.primitives.add(this.a);this.a.destroyPrimitives=!1;A.call(this,a,b)}x(bc,A);k=bc.prototype;k.X=function(a){a.a.counterpart=a;this.a.add(a.a)};k.ba=function(a){a.a.destroy()};k.ja=function(a,b){a.destroy();this.a.destroyPrimitives=b;this.a.remove(a.a);this.a.destroyPrimitives=!1};
k.ia=function(a){if(this.a.destroyPrimitives=a)for(a=0;a<this.a.length;++a)this.a.get(a).counterpart.destroy();this.a.removeAll();this.a.destroyPrimitives=!1};
k.$=function(a){if(!(a instanceof ol.layer.Vector))return null;var b=this.i,c=a.getSource(),d={},e=this.h.ga(a,b,d),f=e.a,g=e.b;g.push(a.on("change:visible",function(){f.show=a.getVisible()}));var h=v(function(c){var g=this.h.Z(a,b,c,e.c);g&&(d[u(c)]=g,f.add(g))},this),l=v(function(a){var b=a.getGeometry();a=u(a);if(!b||"Point"==b.getType()){var b=e.c,c=b.featureToCesiumMap[a];delete b.featureToCesiumMap[a];c instanceof Cesium.Billboard&&b.billboards.remove(c)}b=d[a];delete d[a];null!=b&&f.remove(b)},
this);g.push(c.on("addfeature",function(a){h(a.feature)},this));g.push(c.on("removefeature",function(a){l(a.feature)},this));g.push(c.on("changefeature",function(a){a=a.feature;l(a);h(a)},this));return e};function Z(a){this.j=a.map;this.b=Yb("DIV",{style:"position:absolute;top:0;left:0;width:100%;height:100%;visibility:hidden;"});var b=Ub(a.target||null);if(b)b.appendChild(this.b);else{var c=this.j.getViewport();(c=Vb(c))&&c.parentNode&&c.parentNode.insertBefore(this.b,c)}this.c=null==b;this.s=Yb(sb,{style:"position:absolute;top:0;left:0;width:100%;height:100%;"});this.s.oncontextmenu=function(){return!1};this.s.onselectstart=function(){return!1};this.b.appendChild(this.s);this.v=!1;this.V=[];this.a=
null;this.f=new Cesium.Scene({canvas:this.s,scene3DOnly:!0});b=this.f.screenSpaceCameraController;b.inertiaSpin=0;b.ineartiaTranslate=0;b.inertiaZoom=0;b.tiltEventTypes.push({eventType:Cesium.CameraEventType.LEFT_DRAG,modifier:Cesium.KeyboardEventModifier.SHIFT});b.tiltEventTypes.push({eventType:Cesium.CameraEventType.LEFT_DRAG,modifier:Cesium.KeyboardEventModifier.ALT});b.enableLook=!1;this.f.camera.constrainedAxis=Cesium.Cartesian3.UNIT_Z;this.D=new V(this.f,this.j);this.g=new Cesium.Globe(Cesium.Ellipsoid.WGS84);
this.f.globe=this.g;this.f.skyAtmosphere=new Cesium.SkyAtmosphere;a=n(a.createSynchronizers)?a.createSynchronizers(this.j,this.f):[new ac(this.j,this.f),new bc(this.j,this.f)];for(b=a.length-1;0<=b;--b)a[b].W();this.c&&(a=$b(this.s),null!=a&&(a.style.display="none"));this.D.H();this.J=new R(function(){if(!this.Y){this.f.initializeFrame();var a=this.s.clientWidth,b=this.s.clientHeight;if(this.s.width!==a||this.s.height!==b)this.s.width=a,this.s.height=b,this.f.camera.frustum.aspectRatio=a/b;this.f.render();
this.v&&Jb(this.D)}this.J.start()},void 0,this);this.Y=!1}k=Z.prototype;k.la=function(){return this.D};k.pa=function(){return this.j};k.ma=function(){return this.f};k.oa=function(){return this.v};
k.Da=function(a){if(this.v!=a)if(this.v=a,this.b.style.visibility=this.v?"visible":"hidden",this.v){if(this.c){var b=this.j.getInteractions();b.forEach(function(a){this.V.push(a)},this);b.clear();a=this.j.getLayerGroup();a.getVisible()&&(this.a=a,this.a.setVisible(!1))}this.D.H();this.J.start()}else this.c&&(b=this.j.getInteractions(),z(this.V,function(a){b.push(a)},this),this.V.length=0,null!==this.a&&(this.a.setVisible(!0),this.a=null)),this.D.C(),pb(this.J)};
k.Ia=function(a,b){if(!this.v){this.D.H();var c=this.g.ellipsoid,d=this.f.camera,e=c.cartesianToCartographic(d.position);e.height<a&&(e.height=a,d.position=c.cartographicToCartesian(e));this.J.start();var f=this;setTimeout(function(){!f.v&&pb(f.J)},b)}};k.Ba=function(a){this.Y=a};w("olcs.AbstractSynchronizer",A);A.prototype.synchronize=A.prototype.W;w("olcs.Camera",V);V.prototype.setHeading=V.prototype.Ea;V.prototype.getHeading=V.prototype.ua;V.prototype.setTilt=V.prototype.Fa;V.prototype.getTilt=V.prototype.qa;V.prototype.setDistance=V.prototype.Ca;V.prototype.getDistance=V.prototype.na;V.prototype.setCenter=V.prototype.xa;V.prototype.getCenter=V.prototype.getCenter;V.prototype.setPosition=V.prototype.ya;V.prototype.getPosition=V.prototype.va;V.prototype.setAltitude=V.prototype.Aa;
V.prototype.getAltitude=V.prototype.ha;V.prototype.lookAt=V.prototype.wa;V.prototype.readFromView=V.prototype.H;V.prototype.updateView=V.prototype.C;w("olcs.core.computePixelSizeAtCoordinate",function(a,b){var c=a.camera,d=a.canvas,e=c.frustum,d=new Cesium.Cartesian2(d.width,d.height),c=Cesium.Cartesian3.magnitude(Cesium.Cartesian3.subtract(c.position,b,new Cesium.Cartesian3));return e.getPixelSize(d,c)});
w("olcs.core.applyHeightOffsetToGeometry",function(a,b){a.applyTransform(function(a,d,e){if(n(e)&&3<=e)for(a=0;a<d.length;a+=e)d[a+2]+=b;return d})});w("olcs.core.rotateAroundAxis",vb);
w("olcs.core.setHeadingUsingBottomCenter",function(a,b,c,d){var e=a.camera;a=zb(a,c);a=Cesium.Quaternion.fromAxisAngle(e.right,a);var f=Cesium.Matrix3.fromQuaternion(a),g=new Cesium.Cartesian3;Cesium.Cartesian3.subtract(e.position,c,g);a=new Cesium.Cartesian3;Cesium.Matrix3.multiplyByVector(f,g,a);Cesium.Cartesian3.add(a,c,a);c=Cesium.Matrix4.fromTranslation(a);vb(e,b,a,c,d)});w("olcs.core.pickOnTerrainOrEllipsoid",wb);
w("olcs.core.pickBottomPoint",function(a){var b=a.canvas,b=new Cesium.Cartesian2(b.width/2,b.height);return wb(a,b)});w("olcs.core.pickCenterPoint",xb);
w("olcs.core.computeSignedTiltAngleOnGlobe",function(a){var b=a.camera,c=new Cesium.Ray(b.position,b.direction);a=a.globe.pick(c,a);if(!a){var d=Cesium.IntersectionTests.rayEllipsoid(c,Cesium.Ellipsoid.WGS84);d&&(a=Cesium.Ray.getPoint(c,d.start))}if(a)return c=new Cesium.Cartesian3,Cesium.Ellipsoid.WGS84.geocentricSurfaceNormal(a,c),b=yb(b.direction,c,b.right)-Math.PI,Cesium.Math.convertLongitudeRange(b)});w("olcs.core.computeAngleToZenith",zb);w("olcs.core.lookAt",Ab);
w("olcs.core.extentToRectangle",Bb);w("olcs.core.tileLayerToImageryLayer",Cb);w("olcs.core.updateCesiumLayerProperties",Db);w("olcs.core.ol4326CoordinateToCesiumCartesian",T);w("olcs.core.ol4326CoordinateArrayToCsCartesians",Eb);w("olcs.core.olGeometryCloneTo4326",U);w("olcs.core.convertColorToCesium",Fb);w("olcs.DragBox",X);X.prototype.setScene=X.prototype.Ha;X.prototype.listen=X.prototype.o;w("olcs.FeatureConverter",Y);Y.prototype.csAddBillboard=Y.prototype.aa;
Y.prototype.olCircleGeometryToCesium=Y.prototype.ca;Y.prototype.olLineStringGeometryToCesium=Y.prototype.S;Y.prototype.olPolygonGeometryToCesium=Y.prototype.T;Y.prototype.getHeightReference=Y.prototype.R;Y.prototype.olPointGeometryToCesium=Y.prototype.O;Y.prototype.olMultiGeometryToCesium=Y.prototype.ea;Y.prototype.olGeometry4326TextPartToCesium=Y.prototype.da;Y.prototype.olStyleToCesium=Y.prototype.fa;Y.prototype.computePlainStyle=Y.prototype.P;Y.prototype.olFeatureToCesium=Y.prototype.N;
Y.prototype.olVectorLayerToCesium=Y.prototype.ga;Y.prototype.convert=Y.prototype.Z;w("olcs.OLCesium",Z);Z.prototype.getCamera=Z.prototype.la;Z.prototype.getOlMap=Z.prototype.pa;Z.prototype.getCesiumScene=Z.prototype.ma;Z.prototype.getEnabled=Z.prototype.oa;Z.prototype.setEnabled=Z.prototype.Da;Z.prototype.warmUp=Z.prototype.Ia;Z.prototype.setBlockCesiumRendering=Z.prototype.Ba;w("olcs.RasterSynchronizer",ac);w("olcs.VectorSynchronizer",bc);})();
